name: 'Merge Learning'
on:
  pull_request:
    branches:
      - target_branch
    types:
      - closed
jobs:
  merge_learn_start:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Merge client_build -> amplify (staging)
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: target_branch
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
