name: 'Merge Learning'
on:
  pull_request:
    branches:
      - target_branch
    types:
      - closed
jobs:
  merge_learn_start:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Git Checkout develop
        run: git checkout develop
      - name: Git Merge
        run: git merge target_branch
