name: 'Merge Learning'
on:
  pull_request:
    branches:
      - target_branch
    types:
      - closed
jobs:
  merge_learn_start:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Automatic Merge
        uses: lots0logs/gh-action-auto-merge@1.0.0
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            /merge develop
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
