name: "Merge Amplify Branch"
on:
  pull_request:
    branches:
      - target_branch
    types:
      - closed
permissions: write-all
jobs:
  merge_branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - if: contains(github.event.pull_request.labels.*.name, 'develop')
        name: Branch Merge Main
        uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          source_ref: ${{github.ref}}
          target_branch: develop
          commit_message_template: '[Automated] Merged staging/main | ${{github.event.pull_request.title}}'
