name: 'Merge Learning'
on:
  pull_request:
    branches:
      - target_branch
    types:
      - closed
jobs:
  merge_learn_start:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Branch Merge
        uses: everlytic/branch-merge@1.1.5
        with:
          target_branch: 'develop'
          source_ref: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
