name: 'Merge Learning'
on:
  pull_request:
    branches:
      - target_branch
    types:
      - closed
jobs:
  merge_learn_start:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Direct merge
        uses: tukasz/direct-merge-action@2.0.2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          owner: ${{github.triggering_actor}}
          source-branch: target_branch
          target-branch: develop
          commit-message: '[Automatic] Merge to develop (${{github.actor}})'
